// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFbZKwN8McK21nmO0Aep-EOujuW9QckxY',
    appId: '1:838668296189:web:e8434fa261a59f28a04394',
    messagingSenderId: '838668296189',
    projectId: 'chatapp-fa790',
    authDomain: 'chatapp-fa790.firebaseapp.com',
    storageBucket: 'chatapp-fa790.appspot.com',
    measurementId: 'G-5CPHH5E603',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSUMURrOFyOIcHPqvKCS8hc-pA_Y1VPcE',
    appId: '1:838668296189:android:1a291741b47161a2a04394',
    messagingSenderId: '838668296189',
    projectId: 'chatapp-fa790',
    storageBucket: 'chatapp-fa790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA109MIR8HAOdD25cWwQ_r7nERWHbjiH4M',
    appId: '1:838668296189:ios:0fed49da0064405da04394',
    messagingSenderId: '838668296189',
    projectId: 'chatapp-fa790',
    storageBucket: 'chatapp-fa790.appspot.com',
    androidClientId: '838668296189-bs9cciudq638c54b1alv3pg1rqdspvde.apps.googleusercontent.com',
    iosClientId: '838668296189-pr1mi89lsbhpd7dsmkgoi5vtcbo79t8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.withchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA109MIR8HAOdD25cWwQ_r7nERWHbjiH4M',
    appId: '1:838668296189:ios:0fed49da0064405da04394',
    messagingSenderId: '838668296189',
    projectId: 'chatapp-fa790',
    storageBucket: 'chatapp-fa790.appspot.com',
    androidClientId: '838668296189-bs9cciudq638c54b1alv3pg1rqdspvde.apps.googleusercontent.com',
    iosClientId: '838668296189-pr1mi89lsbhpd7dsmkgoi5vtcbo79t8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.withchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFbZKwN8McK21nmO0Aep-EOujuW9QckxY',
    appId: '1:838668296189:web:2ea0cb11863b6528a04394',
    messagingSenderId: '838668296189',
    projectId: 'chatapp-fa790',
    authDomain: 'chatapp-fa790.firebaseapp.com',
    storageBucket: 'chatapp-fa790.appspot.com',
    measurementId: 'G-GLE14RD1DR',
  );
}
